# $FreeBSD$

PORTNAME=	libmmapi
PORTVERSION=	0.1
CATEGORIES=	devel
MASTER_SITES=	http://www.szerafingomba.hu/softwares/libmmapi/

MAINTAINER=	pozsar.zsolt@szerafingomba.hu
COMMENT=	API for MMxD device

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)
